---
name: Extract and release build artifact

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  extract-artifacts:
    name: Extract u-root (${{ matrix.arch }})
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64]
    uses: bbusse/github-workflows/.github/workflows/container-extract-artifacts.yml@dev
    with:
      wait_for_job: '^Build '
      image: ghcr.io/bbusse/u-root-${{ matrix.arch }}:latest
      release: true
      release_tag: latest
      artifacts: |
        [
          {"path": "u-root-${{ matrix.arch }}",
           "name": "u-root-${{ matrix.arch }}",
           "platform": "linux/${{ matrix.arch }}"},
          {"path": "initramfs-${{ matrix.arch }}.cpio",
           "name": "initramfs-${{ matrix.arch }}.cpio",
           "platform": "linux/${{ matrix.arch }}"}
        ]
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
